// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package smoothing

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufFilterEstimate = []byte{130}

func (t *FilterEstimate) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufFilterEstimate); err != nil {
		return err
	}

	// t.PositionEstimate (big.Int) (struct)
	if err := t.PositionEstimate.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.VelocityEstimate (big.Int) (struct)
	if err := t.VelocityEstimate.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *FilterEstimate) UnmarshalCBOR(r io.Reader) (err error) {
	*t = FilterEstimate{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.PositionEstimate (big.Int) (struct)

	{

		if err := t.PositionEstimate.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.PositionEstimate: %w", err)
		}

	}
	// t.VelocityEstimate (big.Int) (struct)

	{

		if err := t.VelocityEstimate.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.VelocityEstimate: %w", err)
		}

	}
	return nil
}
